### ISSUE TITLE
Hide the New Editor box

### ISSUE THREAD

**Issue by elliott-impression** [wordplate/plate#12]
Hi,

Please add support to hide the new *New Editor* meta box with the `plate-disable-dashboard` hook! This was released in WordPress 4.9.8, in preparation for the Gutenberg release. The box has the ID of `#try-gutenberg-panel`.

<img width="1278" alt="screen shot 2018-08-03 at 11 14 09" src="https://user-images.githubusercontent.com/39268006/43637901-96ca0e42-970e-11e8-83eb-adbc126d1b51.png">

Thanks

**Comment by vinkla** [comment]
Was actually thinking about this myself this morning. Since this is what WordPress call a "call-out" we can't add it to the disable dashboard helper. Instead we can remove Gutenberg with this snippet:

```php
remove_action('try_gutenberg_panel', 'wp_try_gutenberg_panel');
```

Depending on how much WordPress are going to enforce Gutenberg we could look at a long term solution to disable Gutenberg components in this plugin.

**Comment by vinkla** [comment]
If you want to please join the discussion in: https://github.com/wordplate/wordplate/issues/210

**Comment by elliottmangham** [comment]
Super, thanks @vinkla 👏
